### ISSUE TITLE
Which Licence is used for wakeit?

### ISSUE THREAD

**Issue by Borim7** [nathan-osman/wakeit#2]
Hello,

wakeit could be a nice app, but currently I did not get it working. The main annoyance is the missing edit function and help (especially in which format the MAC should be entered).
Its bugged me enough that I want to change this. Currently I managed to build it and I try to get it on my phone.
But before I contribute to the project I want to know which licence is used for wakeit? I did not find any information in the sources. In the app store multiple licences are listed, but I do not know if this is reliable.

P.S.: When building wakeit in-source some source files (e.g.: app/wakeit.desktop.in) are overwritten, is this intended?

**Comment by nathan-osman** [comment]
I've added the license. I'll take a look at the overwriting issue when I'm in front of a computer.
